### PR TITLE
Fix build on device without USB OTG

### PR DESCRIPTION
**Pull request by minicarpet**

### CODE REVIEW

**Comment by MiloradCvjetkovic** [comment]
Hi.
Can you please specify which device you are using?

**Comment by minicarpet** [comment]
Hi, sure, I am building project for STM32L462REYx.

**Comment by minicarpet** [comment]
Hi, yes the build is ok.
but why not using FNR register just as I did ?
I mean USB_FNR contains the frame number from SOF packet. For me, even if HAL does not provides the right function we still can have the value. (page 1540 of reference manual)

**Comment by MiloradCvjetkovic** [comment]
Hi @minicarpet , 
thank you for creating the pull request and helping to improve this repository.
There are 3 reasons for not using FNR :
- it is not device agnostic, some devices with different USB controller do not have FNR as a matter of fact some devices do not even have current frame information in USB controller register at all for the USB Device
- this wrapper tries to use HAL only if possible to make it device agnostic across all device families (there are many)
- current frame information is not essential for the USB Device functionality (it might be used in some rare situations for isochronous endpoint handling) thus since HAL does not support it I have decided not to use it

**Comment by minicarpet** [comment]
Hi,
ok for me, it make sense.
As it compiles now using your commit, we can resolve this PR

**Pull request closed without merging**
